// @ts-nocheck
export default function TermsPage() {
  return (
    <div style={{ fontFamily: 'DM Sans, sans-serif', background: '#fafaf9', minHeight: '100vh', color: '#111' }}>
      <nav style={{ borderBottom: '1px solid #e8e8e4', padding: '0 24px', height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: '#fff' }}>
        <a href="/" style={{ fontSize: 17, fontWeight: 700, letterSpacing: '-0.5px', color: '#111', textDecoration: 'none' }}>bugfix.ai</a>
        <a href="/" style={{ fontSize: 13, color: '#6f6f6a', textDecoration: 'none' }}>Back to home</a>
      </nav>

      <div style={{ maxWidth: 680, margin: '0 auto', padding: '64px 24px 96px' }}>
        <h1 style={{ fontSize: 36, fontWeight: 700, letterSpacing: '-1.5px', marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: '#a3a39e', marginBottom: 48 }}>Last updated: March 2025</p>

        {[
          {
            title: '1. Acceptance of terms',
            body: 'By accessing or using bugfix.ai, you agree to these Terms of Service. If you do not agree, please do not use the service.',
          },
          {
            title: '2. Use of the service',
            body: 'bugfix.ai is a tool for debugging and improving code. You may use it for personal or commercial projects. You agree not to submit code that contains malware, exploits, or content designed to harm others. You agree not to attempt to reverse engineer, overload, or abuse the service.',
          },
          {
            title: '3. Free plan limits',
            body: 'Free users receive 5 fixes per day. This limit resets every 24 hours. We reserve the right to adjust these limits at any time with reasonable notice.',
          },
          {
            title: '4. Paid subscriptions',
            body: 'Paid plans (Plus and Pro) are billed monthly via Stripe. You may cancel at any time from your account. Cancellation takes effect at the end of the current billing period. We do not offer refunds for partial months unless required by law.',
          },
          {
            title: '5. Your code',
            body: 'You retain full ownership of all code you submit to bugfix.ai. We claim no rights over your code. By submitting code, you grant us a limited, temporary license to process it for the purpose of generating a fix.',
          },
          {
            title: '6. Service availability',
            body: 'We aim for high availability but do not guarantee uninterrupted service. The service is provided "as is" without warranty of any kind. We are not liable for any damages resulting from service outages or errors in the AI-generated output.',
          },
          {
            title: '7. AI-generated output',
            body: 'Bug fixes and explanations are generated by AI and may contain errors. You should review all AI-generated code before using it in production. bugfix.ai is not responsible for any bugs, security vulnerabilities, or issues in AI-generated code.',
          },
          {
            title: '8. Changes to terms',
            body: 'We may update these terms from time to time. Continued use of the service after changes are posted constitutes acceptance of the new terms.',
          },
          {
            title: '9. Contact',
            body: 'Questions about these terms? Email hi@bugfix.ai.',
          },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: 36 }}>
            <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 12, letterSpacing: '-0.3px' }}>{section.title}</h2>
            <p style={{ fontSize: 15, color: '#4a4a45', lineHeight: 1.75 }}>{section.body}</p>
          </div>
        ))}
      </div>

      <footer style={{ borderTop: '1px solid #e8e8e4', padding: '24px', textAlign: 'center', background: '#fff' }}>
        <div style={{ fontSize: 13, color: '#a3a39e' }}>
          <a href="/" style={{ color: '#6f6f6a', textDecoration: 'none', marginRight: 20 }}>Home</a>
          <a href="/privacy" style={{ color: '#6f6f6a', textDecoration: 'none', marginRight: 20 }}>Privacy Policy</a>
          <a href="mailto:hi@bugfix.ai" style={{ color: '#6f6f6a', textDecoration: 'none' }}>hi@bugfix.ai</a>
        </div>
        <div style={{ fontSize: 12, color: '#a3a39e', marginTop: 10 }}>&copy; {new Date().getFullYear()} bugfix.ai</div>
      </footer>
    </div>
  )
}
